//
// Generated by Bluespec Compiler, version 2021.07 (build 4cac6eba)
//
// On Thu Apr 25 11:18:11 IST 2024
//
//
// Ports:
// Name                         I/O  size props
// RDY_request_put                O     1
// response_get                   O   512
// RDY_response_get               O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// request_put                    I   512
// EN_request_put                 I     1
// EN_response_get                I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkFFT(CLK,
	     RST_N,

	     request_put,
	     EN_request_put,
	     RDY_request_put,

	     EN_response_get,
	     response_get,
	     RDY_response_get);
  input  CLK;
  input  RST_N;

  // action method request_put
  input  [511 : 0] request_put;
  input  EN_request_put;
  output RDY_request_put;

  // actionvalue method response_get
  input  EN_response_get;
  output [511 : 0] response_get;
  output RDY_response_get;

  // signals for module outputs
  wire [511 : 0] response_get;
  wire RDY_request_put, RDY_response_get;

  // inlined wires
  wire [511 : 0] fft_inputFIFO_wDataIn_wget,
		 fft_inputFIFO_wDataOut_wget,
		 fft_outputFIFO_wDataIn_wget;

  // register fft_inputFIFO_rCache
  reg [514 : 0] fft_inputFIFO_rCache;
  wire [514 : 0] fft_inputFIFO_rCache_D_IN;
  wire fft_inputFIFO_rCache_EN;

  // register fft_inputFIFO_rRdPtr
  reg [1 : 0] fft_inputFIFO_rRdPtr;
  wire [1 : 0] fft_inputFIFO_rRdPtr_D_IN;
  wire fft_inputFIFO_rRdPtr_EN;

  // register fft_inputFIFO_rWrPtr
  reg [1 : 0] fft_inputFIFO_rWrPtr;
  wire [1 : 0] fft_inputFIFO_rWrPtr_D_IN;
  wire fft_inputFIFO_rWrPtr_EN;

  // register fft_outputFIFO_rCache
  reg [514 : 0] fft_outputFIFO_rCache;
  wire [514 : 0] fft_outputFIFO_rCache_D_IN;
  wire fft_outputFIFO_rCache_EN;

  // register fft_outputFIFO_rRdPtr
  reg [1 : 0] fft_outputFIFO_rRdPtr;
  wire [1 : 0] fft_outputFIFO_rRdPtr_D_IN;
  wire fft_outputFIFO_rRdPtr_EN;

  // register fft_outputFIFO_rWrPtr
  reg [1 : 0] fft_outputFIFO_rWrPtr;
  wire [1 : 0] fft_outputFIFO_rWrPtr_D_IN;
  wire fft_outputFIFO_rWrPtr_EN;

  // ports of submodule fft_inputFIFO_memory
  wire [511 : 0] fft_inputFIFO_memory_DIA,
		 fft_inputFIFO_memory_DIB,
		 fft_inputFIFO_memory_DOB;
  wire fft_inputFIFO_memory_ADDRA,
       fft_inputFIFO_memory_ADDRB,
       fft_inputFIFO_memory_ENA,
       fft_inputFIFO_memory_ENB,
       fft_inputFIFO_memory_WEA,
       fft_inputFIFO_memory_WEB;

  // ports of submodule fft_outputFIFO_memory
  wire [511 : 0] fft_outputFIFO_memory_DIA,
		 fft_outputFIFO_memory_DIB,
		 fft_outputFIFO_memory_DOB;
  wire fft_outputFIFO_memory_ADDRA,
       fft_outputFIFO_memory_ADDRB,
       fft_outputFIFO_memory_ENA,
       fft_outputFIFO_memory_ENB,
       fft_outputFIFO_memory_WEA,
       fft_outputFIFO_memory_WEB;

  // rule scheduling signals
  wire CAN_FIRE_RL_fft_comb_fft,
       CAN_FIRE_RL_fft_inputFIFO_portA,
       CAN_FIRE_RL_fft_inputFIFO_portB,
       CAN_FIRE_RL_fft_inputFIFO_portB_read_data,
       CAN_FIRE_RL_fft_outputFIFO_portA,
       CAN_FIRE_RL_fft_outputFIFO_portB,
       CAN_FIRE_RL_fft_outputFIFO_portB_read_data,
       CAN_FIRE_request_put,
       CAN_FIRE_response_get,
       WILL_FIRE_RL_fft_comb_fft,
       WILL_FIRE_RL_fft_inputFIFO_portA,
       WILL_FIRE_RL_fft_inputFIFO_portB,
       WILL_FIRE_RL_fft_inputFIFO_portB_read_data,
       WILL_FIRE_RL_fft_outputFIFO_portA,
       WILL_FIRE_RL_fft_outputFIFO_portB,
       WILL_FIRE_RL_fft_outputFIFO_portB_read_data,
       WILL_FIRE_request_put,
       WILL_FIRE_response_get;

  // remaining internal signals
  wire [63 : 0] IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d475,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d923,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d996,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d316,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d884,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d961,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d1039,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d1080,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d115,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d154,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d196,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d237,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d276,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d356,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d397,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d436,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d517,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d558,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d597,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d640,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d681,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d720,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d74,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d762,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d803,
		_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d842,
		x__h103851,
		x__h112012,
		x__h117969,
		x__h119304,
		x__h138059,
		x__h144016,
		x__h145351,
		x__h164007,
		x__h173180,
		x__h187560,
		x__h190974,
		x__h203690,
		x__h213572,
		x__h228794,
		x__h232196,
		x__h242468,
		x__h269043,
		x__h38247,
		x__h41558,
		x__h64739,
		x__h68050,
		x__h76869,
		x__h80192,
		x__h83609,
		x__h94579,
		x__h97996;
  wire [47 : 0] IF_fft_inputFIFO_wDataOut_wget__8_BITS_159_TO__ETC___d168,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_159_TO__ETC___d776,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_191_TO__ETC___d611,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_191_TO__ETC___d654,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d1010,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d1094,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d489,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d734,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d937,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d1053,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d330,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d856,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d898,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d975,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_415_TO__ETC___d290,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_415_TO__ETC___d695,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_447_TO__ETC___d450,
		IF_fft_inputFIFO_wDataOut_wget__8_BITS_447_TO__ETC___d817,
		IF_fft_inputFIFO_wDataOut_wget__8_BIT_127_0_TH_ETC___d88,
		IF_fft_inputFIFO_wDataOut_wget__8_BIT_223_11_T_ETC___d129,
		IF_fft_inputFIFO_wDataOut_wget__8_BIT_255_54_T_ETC___d572,
		IF_fft_inputFIFO_wDataOut_wget__8_BIT_351_52_T_ETC___d370,
		IF_fft_inputFIFO_wDataOut_wget__8_BIT_383_92_T_ETC___d210,
		IF_fft_inputFIFO_wDataOut_wget__8_BIT_479_33_T_ETC___d251,
		IF_fft_inputFIFO_wDataOut_wget__8_BIT_511_93_T_ETC___d411,
		IF_fft_inputFIFO_wDataOut_wget__8_BIT_95_13_TH_ETC___d531,
		x__h103438,
		x__h111599,
		x__h117556,
		x__h118891,
		x__h137646,
		x__h143603,
		x__h144938,
		x__h163594,
		x__h172767,
		x__h187147,
		x__h190561,
		x__h203277,
		x__h213159,
		x__h228381,
		x__h231783,
		x__h242055,
		x__h268630,
		x__h37834,
		x__h41145,
		x__h64326,
		x__h67637,
		x__h76456,
		x__h79779,
		x__h83196,
		x__h94166,
		x__h97583;
  wire [31 : 0] IF_NOT_IF_NOT_IF_fft_inputFIFO_wDataOut_wget___ETC___d350,
		IF_NOT_IF_NOT_IF_fft_inputFIFO_wDataOut_wget___ETC___d509,
		fft_inputFIFO_wDataOut_wget__8_BITS_159_TO_128_ETC___d150,
		fft_inputFIFO_wDataOut_wget__8_BITS_159_TO_128_ETC___d758,
		fft_inputFIFO_wDataOut_wget__8_BITS_191_TO_160_ETC___d593,
		fft_inputFIFO_wDataOut_wget__8_BITS_191_TO_160_ETC___d636,
		fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d1076,
		fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d471,
		fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d716,
		fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d919,
		fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d1035,
		fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d312,
		fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d838,
		fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d880,
		fft_inputFIFO_wDataOut_wget__8_BITS_415_TO_384_ETC___d272,
		fft_inputFIFO_wDataOut_wget__8_BITS_415_TO_384_ETC___d677,
		fft_inputFIFO_wDataOut_wget__8_BITS_447_TO_416_ETC___d432,
		fft_inputFIFO_wDataOut_wget__8_BITS_447_TO_416_ETC___d799,
		x__h103024,
		x__h103890,
		x__h110212,
		x__h110629,
		x__h111041,
		x__h111185,
		x__h117142,
		x__h118477,
		x__h135480,
		x__h137088,
		x__h137232,
		x__h143189,
		x__h144524,
		x__h164040,
		x__h169914,
		x__h178396,
		x__h178408,
		x__h178420,
		x__h184294,
		x__h190147,
		x__h19603,
		x__h196374,
		x__h196786,
		x__h196919,
		x__h20249,
		x__h202863,
		x__h204187,
		x__h20895,
		x__h210212,
		x__h219539,
		x__h222088,
		x__h222100,
		x__h227967,
		x__h235153,
		x__h235565,
		x__h241641,
		x__h259900,
		x__h259912,
		x__h265777,
		x__h271997,
		x__h272130,
		x__h278991,
		x__h286186,
		x__h292218,
		x__h298452,
		x__h305444,
		x__h312637,
		x__h318668,
		x__h38289,
		x__h48435,
		x__h64781,
		x__h76902,
		x__h76923,
		x__h82782,
		x__h88716,
		x__h91265,
		x__h91277,
		x__h91289,
		x__h91310,
		x__h97169;
  wire [15 : 0] y_f__h104958,
		y_f__h113173,
		y_f__h120465,
		y_f__h125581,
		y_f__h139220,
		y_f__h146512,
		y_f__h151628,
		y_f__h174286,
		y_f__h176915,
		y_f__h188666,
		y_f__h192082,
		y_f__h211277,
		y_f__h220607,
		y_f__h229901,
		y_f__h233301,
		y_f__h250055,
		y_f__h270149,
		y_f__h42667,
		y_f__h45296,
		y_f__h69159,
		y_f__h71788,
		y_f__h81301,
		y_f__h84717,
		y_f__h89784,
		y_f__h95688,
		y_f__h99104;
  wire [1 : 0] x__h12367, x__h14872, x__h3138, x__h5643;

  // action method request_put
  assign RDY_request_put = x__h5643 != fft_inputFIFO_rWrPtr ;
  assign CAN_FIRE_request_put = x__h5643 != fft_inputFIFO_rWrPtr ;
  assign WILL_FIRE_request_put = EN_request_put ;

  // actionvalue method response_get
  assign response_get =
	     (fft_outputFIFO_rCache[514] &&
	      fft_outputFIFO_rCache[513:512] == fft_outputFIFO_rRdPtr) ?
	       fft_outputFIFO_rCache[511:0] :
	       fft_outputFIFO_memory_DOB ;
  assign RDY_response_get = fft_outputFIFO_rRdPtr != fft_outputFIFO_rWrPtr ;
  assign CAN_FIRE_response_get =
	     fft_outputFIFO_rRdPtr != fft_outputFIFO_rWrPtr ;
  assign WILL_FIRE_response_get = EN_response_get ;

  // submodule fft_inputFIFO_memory
  BRAM2 #(.PIPELINED(1'd0),
	  .ADDR_WIDTH(32'd1),
	  .DATA_WIDTH(32'd512),
	  .MEMSIZE(2'd2)) fft_inputFIFO_memory(.CLKA(CLK),
					       .CLKB(CLK),
					       .ADDRA(fft_inputFIFO_memory_ADDRA),
					       .ADDRB(fft_inputFIFO_memory_ADDRB),
					       .DIA(fft_inputFIFO_memory_DIA),
					       .DIB(fft_inputFIFO_memory_DIB),
					       .WEA(fft_inputFIFO_memory_WEA),
					       .WEB(fft_inputFIFO_memory_WEB),
					       .ENA(fft_inputFIFO_memory_ENA),
					       .ENB(fft_inputFIFO_memory_ENB),
					       .DOA(),
					       .DOB(fft_inputFIFO_memory_DOB));

  // submodule fft_outputFIFO_memory
  BRAM2 #(.PIPELINED(1'd0),
	  .ADDR_WIDTH(32'd1),
	  .DATA_WIDTH(32'd512),
	  .MEMSIZE(2'd2)) fft_outputFIFO_memory(.CLKA(CLK),
						.CLKB(CLK),
						.ADDRA(fft_outputFIFO_memory_ADDRA),
						.ADDRB(fft_outputFIFO_memory_ADDRB),
						.DIA(fft_outputFIFO_memory_DIA),
						.DIB(fft_outputFIFO_memory_DIB),
						.WEA(fft_outputFIFO_memory_WEA),
						.WEB(fft_outputFIFO_memory_WEB),
						.ENA(fft_outputFIFO_memory_ENA),
						.ENB(fft_outputFIFO_memory_ENB),
						.DOA(),
						.DOB(fft_outputFIFO_memory_DOB));

  // rule RL_fft_inputFIFO_portB_read_data
  assign CAN_FIRE_RL_fft_inputFIFO_portB_read_data = 1'd1 ;
  assign WILL_FIRE_RL_fft_inputFIFO_portB_read_data = 1'd1 ;

  // rule RL_fft_comb_fft
  assign CAN_FIRE_RL_fft_comb_fft =
	     fft_inputFIFO_rRdPtr != fft_inputFIFO_rWrPtr &&
	     x__h14872 != fft_outputFIFO_rWrPtr ;
  assign WILL_FIRE_RL_fft_comb_fft = CAN_FIRE_RL_fft_comb_fft ;

  // rule RL_fft_inputFIFO_portA
  assign CAN_FIRE_RL_fft_inputFIFO_portA = 1'd1 ;
  assign WILL_FIRE_RL_fft_inputFIFO_portA = 1'd1 ;

  // rule RL_fft_inputFIFO_portB
  assign CAN_FIRE_RL_fft_inputFIFO_portB = 1'd1 ;
  assign WILL_FIRE_RL_fft_inputFIFO_portB = 1'd1 ;

  // rule RL_fft_outputFIFO_portB_read_data
  assign CAN_FIRE_RL_fft_outputFIFO_portB_read_data = 1'd1 ;
  assign WILL_FIRE_RL_fft_outputFIFO_portB_read_data = 1'd1 ;

  // rule RL_fft_outputFIFO_portA
  assign CAN_FIRE_RL_fft_outputFIFO_portA = 1'd1 ;
  assign WILL_FIRE_RL_fft_outputFIFO_portA = 1'd1 ;

  // rule RL_fft_outputFIFO_portB
  assign CAN_FIRE_RL_fft_outputFIFO_portB = 1'd1 ;
  assign WILL_FIRE_RL_fft_outputFIFO_portB = 1'd1 ;

  // inlined wires
  assign fft_inputFIFO_wDataIn_wget =
	     { request_put[511:448],
	       request_put[255:192],
	       request_put[383:320],
	       request_put[127:64],
	       request_put[447:384],
	       request_put[191:128],
	       request_put[319:256],
	       request_put[63:0] } ;
  assign fft_inputFIFO_wDataOut_wget =
	     (fft_inputFIFO_rCache[514] &&
	      fft_inputFIFO_rCache[513:512] == fft_inputFIFO_rRdPtr) ?
	       fft_inputFIFO_rCache[511:0] :
	       fft_inputFIFO_memory_DOB ;
  assign fft_outputFIFO_wDataIn_wget =
	     { x__h19603,
	       x__h91265,
	       x__h110212,
	       x__h178396,
	       x__h196374,
	       x__h222088,
	       x__h235153,
	       x__h259900,
	       x__h271997,
	       x__h278991,
	       x__h286186,
	       x__h292218,
	       x__h298452,
	       x__h305444,
	       x__h312637,
	       x__h318668 } ;

  // register fft_inputFIFO_rCache
  assign fft_inputFIFO_rCache_D_IN =
	     { 1'd1,
	       fft_inputFIFO_rWrPtr,
	       EN_request_put ? fft_inputFIFO_wDataIn_wget : 512'd0 } ;
  assign fft_inputFIFO_rCache_EN = EN_request_put ;

  // register fft_inputFIFO_rRdPtr
  assign fft_inputFIFO_rRdPtr_D_IN = x__h5643 ;
  assign fft_inputFIFO_rRdPtr_EN = CAN_FIRE_RL_fft_comb_fft ;

  // register fft_inputFIFO_rWrPtr
  assign fft_inputFIFO_rWrPtr_D_IN = x__h3138 ;
  assign fft_inputFIFO_rWrPtr_EN = EN_request_put ;

  // register fft_outputFIFO_rCache
  assign fft_outputFIFO_rCache_D_IN =
	     { 1'd1,
	       fft_outputFIFO_rWrPtr,
	       CAN_FIRE_RL_fft_comb_fft ?
		 fft_outputFIFO_wDataIn_wget :
		 512'd0 } ;
  assign fft_outputFIFO_rCache_EN = CAN_FIRE_RL_fft_comb_fft ;

  // register fft_outputFIFO_rRdPtr
  assign fft_outputFIFO_rRdPtr_D_IN = x__h14872 ;
  assign fft_outputFIFO_rRdPtr_EN = EN_response_get ;

  // register fft_outputFIFO_rWrPtr
  assign fft_outputFIFO_rWrPtr_D_IN = x__h12367 ;
  assign fft_outputFIFO_rWrPtr_EN = CAN_FIRE_RL_fft_comb_fft ;

  // submodule fft_inputFIFO_memory
  assign fft_inputFIFO_memory_ADDRA = fft_inputFIFO_rWrPtr[0] ;
  assign fft_inputFIFO_memory_ADDRB =
	     CAN_FIRE_RL_fft_comb_fft ?
	       x__h5643[0] :
	       fft_inputFIFO_rRdPtr[0] ;
  assign fft_inputFIFO_memory_DIA =
	     EN_request_put ? fft_inputFIFO_wDataIn_wget : 512'd0 ;
  assign fft_inputFIFO_memory_DIB = 512'b0 /* unspecified value */  ;
  assign fft_inputFIFO_memory_WEA = EN_request_put ;
  assign fft_inputFIFO_memory_WEB = 1'd0 ;
  assign fft_inputFIFO_memory_ENA = 1'b1 ;
  assign fft_inputFIFO_memory_ENB = 1'b1 ;

  // submodule fft_outputFIFO_memory
  assign fft_outputFIFO_memory_ADDRA = fft_outputFIFO_rWrPtr[0] ;
  assign fft_outputFIFO_memory_ADDRB =
	     EN_response_get ? x__h14872[0] : fft_outputFIFO_rRdPtr[0] ;
  assign fft_outputFIFO_memory_DIA =
	     CAN_FIRE_RL_fft_comb_fft ? fft_outputFIFO_wDataIn_wget : 512'd0 ;
  assign fft_outputFIFO_memory_DIB = 512'b0 /* unspecified value */  ;
  assign fft_outputFIFO_memory_WEA = CAN_FIRE_RL_fft_comb_fft ;
  assign fft_outputFIFO_memory_WEB = 1'd0 ;
  assign fft_outputFIFO_memory_ENA = 1'b1 ;
  assign fft_outputFIFO_memory_ENB = 1'b1 ;

  // remaining internal signals
  assign IF_NOT_IF_NOT_IF_fft_inputFIFO_wDataOut_wget___ETC___d350 =
	     (!x__h103438[47] &&
	      (x__h103438[31] || x__h103438[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h103438[47] &&
		 (!x__h103438[31] || ~x__h103438[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h103438[31:0]) ;
  assign IF_NOT_IF_NOT_IF_fft_inputFIFO_wDataOut_wget___ETC___d509 =
	     (!x__h76456[47] &&
	      (x__h76456[31] || x__h76456[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h76456[47] &&
		 (!x__h76456[31] || ~x__h76456[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h76456[31:0]) ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_159_TO__ETC___d168 =
	     x__h38247[63:16] + { 32'd0, y_f__h45296 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_159_TO__ETC___d776 =
	     x__h187560[63:16] + { 32'd0, y_f__h188666 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_191_TO__ETC___d611 =
	     x__h97996[63:16] + { 32'd0, y_f__h99104 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_191_TO__ETC___d654 =
	     x__h117969[63:16] + { 32'd0, y_f__h125581 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d1010 =
	     x__h232196[63:16] + { 32'd0, y_f__h233301 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d1094 =
	     x__h269043[63:16] + { 32'd0, y_f__h270149 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d475 =
	     x__h88716 * 32'd46341 ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d489 =
	     x__h76869[63:16] + { 32'd0, y_f__h89784 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d734 =
	     x__h164007[63:16] + { 32'd0, y_f__h176915 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d923 =
	     x__h219539 * 32'd46341 ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d937 =
	     x__h213572[63:16] + { 32'd0, y_f__h220607 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d996 =
	     x__h219539 * 32'd46340 ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d1053 =
	     x__h242468[63:16] + { 32'd0, y_f__h250055 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d316 =
	     x__h103890 * 32'd46341 ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d330 =
	     x__h103851[63:16] + { 32'd0, y_f__h104958 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d856 =
	     x__h190974[63:16] + { 32'd0, y_f__h192082 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d884 =
	     x__h210212 * 32'd46340 ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d898 =
	     x__h203690[63:16] + { 32'd0, y_f__h211277 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d961 =
	     x__h210212 * 32'd46341 ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d975 =
	     x__h228794[63:16] + { 32'd0, y_f__h229901 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_415_TO__ETC___d290 =
	     x__h64739[63:16] + { 32'd0, y_f__h71788 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_415_TO__ETC___d695 =
	     x__h173180[63:16] + { 32'd0, y_f__h174286 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_447_TO__ETC___d450 =
	     x__h83609[63:16] + { 32'd0, y_f__h84717 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BITS_447_TO__ETC___d817 =
	     x__h144016[63:16] + { 32'd0, y_f__h151628 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BIT_127_0_TH_ETC___d88 =
	     x__h112012[63:16] + { 32'd0, y_f__h113173 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BIT_223_11_T_ETC___d129 =
	     x__h41558[63:16] + { 32'd0, y_f__h42667 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BIT_255_54_T_ETC___d572 =
	     x__h119304[63:16] + { 32'd0, y_f__h120465 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BIT_351_52_T_ETC___d370 =
	     x__h80192[63:16] + { 32'd0, y_f__h81301 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BIT_383_92_T_ETC___d210 =
	     x__h138059[63:16] + { 32'd0, y_f__h139220 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BIT_479_33_T_ETC___d251 =
	     x__h68050[63:16] + { 32'd0, y_f__h69159 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BIT_511_93_T_ETC___d411 =
	     x__h145351[63:16] + { 32'd0, y_f__h146512 } ;
  assign IF_fft_inputFIFO_wDataOut_wget__8_BIT_95_13_TH_ETC___d531 =
	     x__h94579[63:16] + { 32'd0, y_f__h95688 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d1039 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d1035[31] ?
		 -fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d1035 :
		 fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d1035,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d1080 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d1076[31] ?
		 -fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d1076 :
		 fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d1076,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d115 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget[223] ?
		 -fft_inputFIFO_wDataOut_wget[223:192] :
		 fft_inputFIFO_wDataOut_wget[223:192],
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d154 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget__8_BITS_159_TO_128_ETC___d150[31] ?
		 -fft_inputFIFO_wDataOut_wget__8_BITS_159_TO_128_ETC___d150 :
		 fft_inputFIFO_wDataOut_wget__8_BITS_159_TO_128_ETC___d150,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d196 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget[383] ?
		 -fft_inputFIFO_wDataOut_wget[383:352] :
		 fft_inputFIFO_wDataOut_wget[383:352],
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d237 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget[479] ?
		 -fft_inputFIFO_wDataOut_wget[479:448] :
		 fft_inputFIFO_wDataOut_wget[479:448],
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d276 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget__8_BITS_415_TO_384_ETC___d272[31] ?
		 -fft_inputFIFO_wDataOut_wget__8_BITS_415_TO_384_ETC___d272 :
		 fft_inputFIFO_wDataOut_wget__8_BITS_415_TO_384_ETC___d272,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d356 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget[351] ?
		 -fft_inputFIFO_wDataOut_wget[351:320] :
		 fft_inputFIFO_wDataOut_wget[351:320],
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d397 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget[511] ?
		 -fft_inputFIFO_wDataOut_wget[511:480] :
		 fft_inputFIFO_wDataOut_wget[511:480],
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d436 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget__8_BITS_447_TO_416_ETC___d432[31] ?
		 -fft_inputFIFO_wDataOut_wget__8_BITS_447_TO_416_ETC___d432 :
		 fft_inputFIFO_wDataOut_wget__8_BITS_447_TO_416_ETC___d432,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d517 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget[95] ?
		 -fft_inputFIFO_wDataOut_wget[95:64] :
		 fft_inputFIFO_wDataOut_wget[95:64],
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d558 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget[255] ?
		 -fft_inputFIFO_wDataOut_wget[255:224] :
		 fft_inputFIFO_wDataOut_wget[255:224],
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d597 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget__8_BITS_191_TO_160_ETC___d593[31] ?
		 -fft_inputFIFO_wDataOut_wget__8_BITS_191_TO_160_ETC___d593 :
		 fft_inputFIFO_wDataOut_wget__8_BITS_191_TO_160_ETC___d593,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d640 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget__8_BITS_191_TO_160_ETC___d636[31] ?
		 -fft_inputFIFO_wDataOut_wget__8_BITS_191_TO_160_ETC___d636 :
		 fft_inputFIFO_wDataOut_wget__8_BITS_191_TO_160_ETC___d636,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d681 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget__8_BITS_415_TO_384_ETC___d677[31] ?
		 -fft_inputFIFO_wDataOut_wget__8_BITS_415_TO_384_ETC___d677 :
		 fft_inputFIFO_wDataOut_wget__8_BITS_415_TO_384_ETC___d677,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d720 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d716[31] ?
		 -fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d716 :
		 fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d716,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d74 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget[127] ?
		 -fft_inputFIFO_wDataOut_wget[127:96] :
		 fft_inputFIFO_wDataOut_wget[127:96],
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d762 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget__8_BITS_159_TO_128_ETC___d758[31] ?
		 -fft_inputFIFO_wDataOut_wget__8_BITS_159_TO_128_ETC___d758 :
		 fft_inputFIFO_wDataOut_wget__8_BITS_159_TO_128_ETC___d758,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d803 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget__8_BITS_447_TO_416_ETC___d799[31] ?
		 -fft_inputFIFO_wDataOut_wget__8_BITS_447_TO_416_ETC___d799 :
		 fft_inputFIFO_wDataOut_wget__8_BITS_447_TO_416_ETC___d799,
	       16'd0 } ;
  assign _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d842 =
	     { 16'd0,
	       fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d838[31] ?
		 -fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d838 :
		 fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d838,
	       16'd0 } ;
  assign fft_inputFIFO_wDataOut_wget__8_BITS_159_TO_128_ETC___d150 =
	     fft_inputFIFO_wDataOut_wget[159:128] - x__h38289 ;
  assign fft_inputFIFO_wDataOut_wget__8_BITS_159_TO_128_ETC___d758 =
	     fft_inputFIFO_wDataOut_wget[159:128] + x__h38289 ;
  assign fft_inputFIFO_wDataOut_wget__8_BITS_191_TO_160_ETC___d593 =
	     fft_inputFIFO_wDataOut_wget[191:160] - x__h118477 ;
  assign fft_inputFIFO_wDataOut_wget__8_BITS_191_TO_160_ETC___d636 =
	     fft_inputFIFO_wDataOut_wget[191:160] + x__h118477 ;
  assign fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d1076 =
	     x__h164040 + x__h169914 ;
  assign fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d471 =
	     x__h76902 - x__h82782 ;
  assign fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d716 =
	     x__h164040 - x__h169914 ;
  assign fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d919 =
	     x__h76902 + x__h82782 ;
  assign fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d1035 =
	     x__h137088 + x__h143189 ;
  assign fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d312 =
	     x__h48435 - x__h204187 ;
  assign fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d838 =
	     x__h137088 - x__h143189 ;
  assign fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d880 =
	     x__h48435 + x__h204187 ;
  assign fft_inputFIFO_wDataOut_wget__8_BITS_415_TO_384_ETC___d272 =
	     fft_inputFIFO_wDataOut_wget[415:384] - x__h64781 ;
  assign fft_inputFIFO_wDataOut_wget__8_BITS_415_TO_384_ETC___d677 =
	     fft_inputFIFO_wDataOut_wget[415:384] + x__h64781 ;
  assign fft_inputFIFO_wDataOut_wget__8_BITS_447_TO_416_ETC___d432 =
	     fft_inputFIFO_wDataOut_wget[447:416] - x__h144524 ;
  assign fft_inputFIFO_wDataOut_wget__8_BITS_447_TO_416_ETC___d799 =
	     fft_inputFIFO_wDataOut_wget[447:416] + x__h144524 ;
  assign x__h103024 =
	     IF_NOT_IF_NOT_IF_fft_inputFIFO_wDataOut_wget___ETC___d350 +
	     IF_NOT_IF_NOT_IF_fft_inputFIFO_wDataOut_wget___ETC___d509 ;
  assign x__h103438 =
	     (!x__h103851[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d330[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d330 ;
  assign x__h103851 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d312[31] ?
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d316 :
	       -IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d316 ;
  assign x__h103890 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d312[31] ?
	       -fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d312 :
	       fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d312 ;
  assign x__h110212 = x__h110629 - x__h135480 ;
  assign x__h110629 = x__h111041 - x__h117142 ;
  assign x__h111041 = fft_inputFIFO_wDataOut_wget[63:32] + x__h111185 ;
  assign x__h111185 =
	     (!x__h111599[47] &&
	      (x__h111599[31] || x__h111599[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h111599[47] &&
		 (!x__h111599[31] || ~x__h111599[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h111599[31:0]) ;
  assign x__h111599 =
	     (!x__h112012[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BIT_127_0_TH_ETC___d88[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BIT_127_0_TH_ETC___d88 ;
  assign x__h112012 =
	     fft_inputFIFO_wDataOut_wget[127] ?
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d74 :
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d74 ;
  assign x__h117142 =
	     (!x__h117556[47] &&
	      (x__h117556[31] || x__h117556[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h117556[47] &&
		 (!x__h117556[31] || ~x__h117556[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h117556[31:0]) ;
  assign x__h117556 =
	     (!x__h117969[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BITS_191_TO__ETC___d654[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_191_TO__ETC___d654 ;
  assign x__h117969 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_191_TO_160_ETC___d636[31] ?
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d640 :
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d640 ;
  assign x__h118477 =
	     (!x__h118891[47] &&
	      (x__h118891[31] || x__h118891[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h118891[47] &&
		 (!x__h118891[31] || ~x__h118891[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h118891[31:0]) ;
  assign x__h118891 =
	     (!x__h119304[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BIT_255_54_T_ETC___d572[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BIT_255_54_T_ETC___d572 ;
  assign x__h119304 =
	     fft_inputFIFO_wDataOut_wget[255] ?
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d558 :
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d558 ;
  assign x__h12367 = fft_outputFIFO_rWrPtr + 2'd1 ;
  assign x__h135480 =
	     32'd0 -
	     ((!x__h163594[47] &&
	       (x__h163594[31] || x__h163594[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h163594[47] &&
		  (!x__h163594[31] || ~x__h163594[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h163594[31:0])) ;
  assign x__h137088 = fft_inputFIFO_wDataOut_wget[319:288] + x__h137232 ;
  assign x__h137232 =
	     (!x__h137646[47] &&
	      (x__h137646[31] || x__h137646[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h137646[47] &&
		 (!x__h137646[31] || ~x__h137646[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h137646[31:0]) ;
  assign x__h137646 =
	     (!x__h138059[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BIT_383_92_T_ETC___d210[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BIT_383_92_T_ETC___d210 ;
  assign x__h138059 =
	     fft_inputFIFO_wDataOut_wget[383] ?
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d196 :
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d196 ;
  assign x__h143189 =
	     (!x__h143603[47] &&
	      (x__h143603[31] || x__h143603[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h143603[47] &&
		 (!x__h143603[31] || ~x__h143603[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h143603[31:0]) ;
  assign x__h143603 =
	     (!x__h144016[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BITS_447_TO__ETC___d817[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_447_TO__ETC___d817 ;
  assign x__h144016 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_447_TO_416_ETC___d799[31] ?
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d803 :
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d803 ;
  assign x__h144524 =
	     (!x__h144938[47] &&
	      (x__h144938[31] || x__h144938[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h144938[47] &&
		 (!x__h144938[31] || ~x__h144938[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h144938[31:0]) ;
  assign x__h144938 =
	     (!x__h145351[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BIT_511_93_T_ETC___d411[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BIT_511_93_T_ETC___d411 ;
  assign x__h145351 =
	     fft_inputFIFO_wDataOut_wget[511] ?
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d397 :
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d397 ;
  assign x__h14872 = fft_outputFIFO_rRdPtr + 2'd1 ;
  assign x__h163594 =
	     (!x__h164007[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d734[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d734 ;
  assign x__h164007 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d716[31] ?
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d720 :
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d720 ;
  assign x__h164040 = fft_inputFIFO_wDataOut_wget[287:256] + x__h76923 ;
  assign x__h169914 =
	     (!x__h172767[47] &&
	      (x__h172767[31] || x__h172767[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h172767[47] &&
		 (!x__h172767[31] || ~x__h172767[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h172767[31:0]) ;
  assign x__h172767 =
	     (!x__h173180[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BITS_415_TO__ETC___d695[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_415_TO__ETC___d695 ;
  assign x__h173180 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_415_TO_384_ETC___d677[31] ?
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d681 :
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d681 ;
  assign x__h178396 = x__h178408 - x__h190147 ;
  assign x__h178408 = x__h178420 - x__h184294 ;
  assign x__h178420 = fft_inputFIFO_wDataOut_wget[31:0] + x__h91310 ;
  assign x__h184294 =
	     (!x__h187147[47] &&
	      (x__h187147[31] || x__h187147[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h187147[47] &&
		 (!x__h187147[31] || ~x__h187147[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h187147[31:0]) ;
  assign x__h187147 =
	     (!x__h187560[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BITS_159_TO__ETC___d776[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_159_TO__ETC___d776 ;
  assign x__h187560 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_159_TO_128_ETC___d758[31] ?
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d762 :
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d762 ;
  assign x__h190147 =
	     (!x__h190561[47] &&
	      (x__h190561[31] || x__h190561[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h190561[47] &&
		 (!x__h190561[31] || ~x__h190561[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h190561[31:0]) ;
  assign x__h190561 =
	     (!x__h190974[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d856[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d856 ;
  assign x__h190974 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d838[31] ?
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d842 :
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d842 ;
  assign x__h19603 = x__h20249 - x__h272130 ;
  assign x__h196374 = x__h196786 - x__h202863 ;
  assign x__h196786 = x__h20895 + x__h196919 ;
  assign x__h196919 =
	     32'd0 -
	     ((!x__h37834[47] &&
	       (x__h37834[31] || x__h37834[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h37834[47] &&
		  (!x__h37834[31] || ~x__h37834[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h37834[31:0])) ;
  assign x__h20249 = x__h20895 - x__h196919 ;
  assign x__h202863 =
	     ((!x__h203277[47] &&
	       (x__h203277[31] || x__h203277[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h203277[47] &&
		  (!x__h203277[31] || ~x__h203277[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h203277[31:0])) -
	     ((!x__h213159[47] &&
	       (x__h213159[31] || x__h213159[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h213159[47] &&
		  (!x__h213159[31] || ~x__h213159[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h213159[31:0])) ;
  assign x__h203277 =
	     (!x__h203690[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d898[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d898 ;
  assign x__h203690 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d880[31] ?
	       -IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d884 :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d884 ;
  assign x__h204187 =
	     32'd0 -
	     ((!x__h64326[47] &&
	       (x__h64326[31] || x__h64326[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h64326[47] &&
		  (!x__h64326[31] || ~x__h64326[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h64326[31:0])) ;
  assign x__h20895 = fft_inputFIFO_wDataOut_wget[63:32] - x__h111185 ;
  assign x__h210212 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d880[31] ?
	       -fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d880 :
	       fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d880 ;
  assign x__h213159 =
	     (!x__h213572[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d937[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d937 ;
  assign x__h213572 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d919[31] ?
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d923 :
	       -IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d923 ;
  assign x__h219539 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d919[31] ?
	       -fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d919 :
	       fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d919 ;
  assign x__h222088 = x__h222100 - x__h227967 ;
  assign x__h222100 = x__h91289 + x__h97169 ;
  assign x__h227967 =
	     ((!x__h228381[47] &&
	       (x__h228381[31] || x__h228381[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h228381[47] &&
		  (!x__h228381[31] || ~x__h228381[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h228381[31:0])) +
	     ((!x__h231783[47] &&
	       (x__h231783[31] || x__h231783[47:32] != 16'd0)) ?
		32'h7FFFFFFF :
		((x__h231783[47] &&
		  (!x__h231783[31] || ~x__h231783[47:32] != 16'd0)) ?
		   32'h80000000 :
		   x__h231783[31:0])) ;
  assign x__h228381 =
	     (!x__h228794[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d975[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d975 ;
  assign x__h228794 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d880[31] ?
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d961 :
	       -IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d961 ;
  assign x__h231783 =
	     (!x__h232196[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d1010[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d1010 ;
  assign x__h232196 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d919[31] ?
	       -IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d996 :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d996 ;
  assign x__h235153 = x__h235565 - x__h241641 ;
  assign x__h235565 = x__h111041 + x__h117142 ;
  assign x__h241641 =
	     (!x__h242055[47] &&
	      (x__h242055[31] || x__h242055[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h242055[47] &&
		 (!x__h242055[31] || ~x__h242055[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h242055[31:0]) ;
  assign x__h242055 =
	     (!x__h242468[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d1053[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_319_TO__ETC___d1053 ;
  assign x__h242468 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_319_TO_288_ETC___d1035[31] ?
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d1039 :
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d1039 ;
  assign x__h259900 = x__h259912 - x__h265777 ;
  assign x__h259912 = x__h178420 + x__h184294 ;
  assign x__h265777 =
	     (!x__h268630[47] &&
	      (x__h268630[31] || x__h268630[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h268630[47] &&
		 (!x__h268630[31] || ~x__h268630[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h268630[31:0]) ;
  assign x__h268630 =
	     (!x__h269043[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d1094[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d1094 ;
  assign x__h269043 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d1076[31] ?
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d1080 :
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d1080 ;
  assign x__h271997 = x__h20249 + x__h272130 ;
  assign x__h272130 =
	     IF_NOT_IF_NOT_IF_fft_inputFIFO_wDataOut_wget___ETC___d350 -
	     IF_NOT_IF_NOT_IF_fft_inputFIFO_wDataOut_wget___ETC___d509 ;
  assign x__h278991 = x__h91277 + x__h103024 ;
  assign x__h286186 = x__h110629 + x__h135480 ;
  assign x__h292218 = x__h178408 + x__h190147 ;
  assign x__h298452 = x__h196786 + x__h202863 ;
  assign x__h305444 = x__h222100 + x__h227967 ;
  assign x__h312637 = x__h235565 + x__h241641 ;
  assign x__h3138 = fft_inputFIFO_rWrPtr + 2'd1 ;
  assign x__h318668 = x__h259912 + x__h265777 ;
  assign x__h37834 =
	     (!x__h38247[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BITS_159_TO__ETC___d168[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_159_TO__ETC___d168 ;
  assign x__h38247 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_159_TO_128_ETC___d150[31] ?
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d154 :
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d154 ;
  assign x__h38289 =
	     (!x__h41145[47] &&
	      (x__h41145[31] || x__h41145[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h41145[47] &&
		 (!x__h41145[31] || ~x__h41145[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h41145[31:0]) ;
  assign x__h41145 =
	     (!x__h41558[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BIT_223_11_T_ETC___d129[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BIT_223_11_T_ETC___d129 ;
  assign x__h41558 =
	     fft_inputFIFO_wDataOut_wget[223] ?
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d115 :
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d115 ;
  assign x__h48435 = fft_inputFIFO_wDataOut_wget[319:288] - x__h137232 ;
  assign x__h5643 = fft_inputFIFO_rRdPtr + 2'd1 ;
  assign x__h64326 =
	     (!x__h64739[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BITS_415_TO__ETC___d290[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_415_TO__ETC___d290 ;
  assign x__h64739 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_415_TO_384_ETC___d272[31] ?
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d276 :
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d276 ;
  assign x__h64781 =
	     (!x__h67637[47] &&
	      (x__h67637[31] || x__h67637[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h67637[47] &&
		 (!x__h67637[31] || ~x__h67637[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h67637[31:0]) ;
  assign x__h67637 =
	     (!x__h68050[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BIT_479_33_T_ETC___d251[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BIT_479_33_T_ETC___d251 ;
  assign x__h68050 =
	     fft_inputFIFO_wDataOut_wget[479] ?
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d237 :
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d237 ;
  assign x__h76456 =
	     (!x__h76869[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d489[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d489 ;
  assign x__h76869 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d471[31] ?
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d475 :
	       -IF_fft_inputFIFO_wDataOut_wget__8_BITS_287_TO__ETC___d475 ;
  assign x__h76902 = fft_inputFIFO_wDataOut_wget[287:256] - x__h76923 ;
  assign x__h76923 =
	     (!x__h79779[47] &&
	      (x__h79779[31] || x__h79779[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h79779[47] &&
		 (!x__h79779[31] || ~x__h79779[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h79779[31:0]) ;
  assign x__h79779 =
	     (!x__h80192[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BIT_351_52_T_ETC___d370[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BIT_351_52_T_ETC___d370 ;
  assign x__h80192 =
	     fft_inputFIFO_wDataOut_wget[351] ?
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d356 :
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d356 ;
  assign x__h82782 =
	     (!x__h83196[47] &&
	      (x__h83196[31] || x__h83196[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h83196[47] &&
		 (!x__h83196[31] || ~x__h83196[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h83196[31:0]) ;
  assign x__h83196 =
	     (!x__h83609[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BITS_447_TO__ETC___d450[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_447_TO__ETC___d450 ;
  assign x__h83609 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_447_TO_416_ETC___d432[31] ?
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d436 :
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d436 ;
  assign x__h88716 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d471[31] ?
	       -fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d471 :
	       fft_inputFIFO_wDataOut_wget__8_BITS_287_TO_256_ETC___d471 ;
  assign x__h91265 = x__h91277 - x__h103024 ;
  assign x__h91277 = x__h91289 - x__h97169 ;
  assign x__h91289 = fft_inputFIFO_wDataOut_wget[31:0] - x__h91310 ;
  assign x__h91310 =
	     (!x__h94166[47] &&
	      (x__h94166[31] || x__h94166[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h94166[47] &&
		 (!x__h94166[31] || ~x__h94166[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h94166[31:0]) ;
  assign x__h94166 =
	     (!x__h94579[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BIT_95_13_TH_ETC___d531[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BIT_95_13_TH_ETC___d531 ;
  assign x__h94579 =
	     fft_inputFIFO_wDataOut_wget[95] ?
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d517 :
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d517 ;
  assign x__h97169 =
	     (!x__h97583[47] &&
	      (x__h97583[31] || x__h97583[47:32] != 16'd0)) ?
	       32'h7FFFFFFF :
	       ((x__h97583[47] &&
		 (!x__h97583[31] || ~x__h97583[47:32] != 16'd0)) ?
		  32'h80000000 :
		  x__h97583[31:0]) ;
  assign x__h97583 =
	     (!x__h97996[63] &&
	      IF_fft_inputFIFO_wDataOut_wget__8_BITS_191_TO__ETC___d611[47]) ?
	       48'h7FFFFFFFFFFF :
	       IF_fft_inputFIFO_wDataOut_wget__8_BITS_191_TO__ETC___d611 ;
  assign x__h97996 =
	     fft_inputFIFO_wDataOut_wget__8_BITS_191_TO_160_ETC___d593[31] ?
	       _0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d597 :
	       -_0_CONCAT_IF_fft_inputFIFO_wDataOut_wget__8_BIT_ETC___d597 ;
  assign y_f__h104958 =
	     (x__h103851[15] &&
	      (x__h103851[63] || x__h103851[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h113173 =
	     (x__h112012[15] &&
	      (x__h112012[63] || x__h112012[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h120465 =
	     (x__h119304[15] &&
	      (x__h119304[63] || x__h119304[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h125581 =
	     (x__h117969[15] &&
	      (x__h117969[63] || x__h117969[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h139220 =
	     (x__h138059[15] &&
	      (x__h138059[63] || x__h138059[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h146512 =
	     (x__h145351[15] &&
	      (x__h145351[63] || x__h145351[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h151628 =
	     (x__h144016[15] &&
	      (x__h144016[63] || x__h144016[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h174286 =
	     (x__h173180[15] &&
	      (x__h173180[63] || x__h173180[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h176915 =
	     (x__h164007[15] &&
	      (x__h164007[63] || x__h164007[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h188666 =
	     (x__h187560[15] &&
	      (x__h187560[63] || x__h187560[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h192082 =
	     (x__h190974[15] &&
	      (x__h190974[63] || x__h190974[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h211277 =
	     (x__h203690[15] &&
	      (x__h203690[63] || x__h203690[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h220607 =
	     (x__h213572[15] &&
	      (x__h213572[63] || x__h213572[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h229901 =
	     (x__h228794[15] &&
	      (x__h228794[63] || x__h228794[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h233301 =
	     (x__h232196[15] &&
	      (x__h232196[63] || x__h232196[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h250055 =
	     (x__h242468[15] &&
	      (x__h242468[63] || x__h242468[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h270149 =
	     (x__h269043[15] &&
	      (x__h269043[63] || x__h269043[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h42667 =
	     (x__h41558[15] && (x__h41558[63] || x__h41558[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h45296 =
	     (x__h38247[15] && (x__h38247[63] || x__h38247[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h69159 =
	     (x__h68050[15] && (x__h68050[63] || x__h68050[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h71788 =
	     (x__h64739[15] && (x__h64739[63] || x__h64739[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h81301 =
	     (x__h80192[15] && (x__h80192[63] || x__h80192[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h84717 =
	     (x__h83609[15] && (x__h83609[63] || x__h83609[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h89784 =
	     (x__h76869[15] && (x__h76869[63] || x__h76869[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h95688 =
	     (x__h94579[15] && (x__h94579[63] || x__h94579[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;
  assign y_f__h99104 =
	     (x__h97996[15] && (x__h97996[63] || x__h97996[14:0] != 15'd0)) ?
	       16'd1 :
	       16'd0 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        fft_inputFIFO_rCache <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0, 514'b0 /* unspecified value */  };
	fft_inputFIFO_rRdPtr <= `BSV_ASSIGNMENT_DELAY 2'd0;
	fft_inputFIFO_rWrPtr <= `BSV_ASSIGNMENT_DELAY 2'd0;
	fft_outputFIFO_rCache <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0, 514'b0 /* unspecified value */  };
	fft_outputFIFO_rRdPtr <= `BSV_ASSIGNMENT_DELAY 2'd0;
	fft_outputFIFO_rWrPtr <= `BSV_ASSIGNMENT_DELAY 2'd0;
      end
    else
      begin
        if (fft_inputFIFO_rCache_EN)
	  fft_inputFIFO_rCache <= `BSV_ASSIGNMENT_DELAY
	      fft_inputFIFO_rCache_D_IN;
	if (fft_inputFIFO_rRdPtr_EN)
	  fft_inputFIFO_rRdPtr <= `BSV_ASSIGNMENT_DELAY
	      fft_inputFIFO_rRdPtr_D_IN;
	if (fft_inputFIFO_rWrPtr_EN)
	  fft_inputFIFO_rWrPtr <= `BSV_ASSIGNMENT_DELAY
	      fft_inputFIFO_rWrPtr_D_IN;
	if (fft_outputFIFO_rCache_EN)
	  fft_outputFIFO_rCache <= `BSV_ASSIGNMENT_DELAY
	      fft_outputFIFO_rCache_D_IN;
	if (fft_outputFIFO_rRdPtr_EN)
	  fft_outputFIFO_rRdPtr <= `BSV_ASSIGNMENT_DELAY
	      fft_outputFIFO_rRdPtr_D_IN;
	if (fft_outputFIFO_rWrPtr_EN)
	  fft_outputFIFO_rWrPtr <= `BSV_ASSIGNMENT_DELAY
	      fft_outputFIFO_rWrPtr_D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    fft_inputFIFO_rCache =
	515'h2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    fft_inputFIFO_rRdPtr = 2'h2;
    fft_inputFIFO_rWrPtr = 2'h2;
    fft_outputFIFO_rCache =
	515'h2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    fft_outputFIFO_rRdPtr = 2'h2;
    fft_outputFIFO_rWrPtr = 2'h2;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkFFT

